parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect
  import/internal-regex: ^@optibus

plugins:
  - import
  - react-hooks

extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:react/recommended

rules:
  prefer-template:
    - error
  'import/order':
    - 'error'
    - 
      'newlines-between': 'always'
      pathGroups: [
        {
          pattern: '~/**',
          group: 'index',
          position: 'after'
        },
        {
          pattern: '@optibus/**',
          group: 'index',
          position: 'before'
        },
      ]
      groups: ['builtin', 'external', 'internal', 'index', 'object', ['parent', 'sibling']]
       # object, index, sibling, parent, internal, external, 
  prettier/prettier:
    - error
  no-console:
    - warn
    - allow:
        - warn
        - error
    #     - info
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-empty-interface': error
  '@typescript-eslint/no-use-before-define': [error, { functions: false }]
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  react/prop-types:
    - off
  react/react-in-jsx-scope: 
    - off
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps':
    - warn
    
  'react/jsx-filename-extension':
    - error
    - extensions:
        - '.tsx'
        - '.jsx'

ignorePatterns:
  - dist/**/*
  - build/**/*
  - generated/**/*
  - .storybook/*.js
